- name: Install python3-mysqldb
  apt:
    name: python3-mysqldb
    state: present

- name: Set MySQL root password & ensure root auth
  mysql_user:
    login_user: "root"
    login_password: ""
    user: "root"
    password: "{{ mysql_root_password }}"
    host_all: yes

- name: Create application users
  mysql_user:
    login_user: "root"
    login_password: "{{ mysql_root_password }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "{{ item.host }}"
    priv: "{{ item.priv }}"
    state: present
  loop: "{{ mysql_users }}"
